### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by khallmark** [wxdao/CS2-ByeByeHomelessMod#2]
Would you be so kind as to push the latest source code?

**Comment by khallmark** [comment]
thanks!

**Comment by wxdao** [comment]
Sorry about that! I forgot to push the source code for version 2.1.0. Will push it later today.

**Comment by khallmark** [comment]
@wxdao Just wanted to take a moment to thank you for keeping the source code up to date. I've been keeping an eye on this mod and it's helped me understand the simulation and the issue better. I was really glad to see an update after I started to notice some of the same problems again. I appreciate you.
